
/* Macro Tracker v1.1.3 */
const APP_VERSION="v1.1.3";
const STORAGE_KEY="macro-tracker:data",UNDO_STACK_KEY="macro-tracker:undoStack",REDO_STACK_KEY="macro-tracker:redoStack",SETTINGS_KEY="macro-tracker:settings",PRESETS_KEY="macro-tracker:presets";const SCHEMA_VERSION=3;
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));const todayISO=()=>new Date().toISOString().slice(0,10);const nowHM=()=>{const d=new Date();return String(d.getHours()).padStart(2,"0")+":"+String(d.getMinutes()).padStart(2,"0")};const clamp=(n,min,max)=>Math.min(Math.max(n,min),max);
function defaultSettings(){return{targets:{cal:2000,p:150,c:200,f:70},theme:"light",showRemaining:false}}function loadSettings(){try{return JSON.parse(localStorage.getItem(SETTINGS_KEY))||defaultSettings()}catch(e){return defaultSettings()}}function saveSettings(s){localStorage.setItem(SETTINGS_KEY,JSON.stringify(s))}function applyTheme(){const s=loadSettings();document.documentElement.removeAttribute("data-theme");if(s.theme==="light")document.documentElement.setAttribute("data-theme","light");else if(s.theme==="dark")document.documentElement.setAttribute("data-theme","dark")}
function loadRaw(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"null")}catch(e){return null}}function loadMeals(){const raw=loadRaw();if(!raw)return[];if(raw.schemaVersion!==SCHEMA_VERSION){if(Array.isArray(raw)){const m={schemaVersion:SCHEMA_VERSION,meals:raw};localStorage.setItem(STORAGE_KEY,JSON.stringify(m));return m.meals}if(raw.meals){raw.schemaVersion=SCHEMA_VERSION;localStorage.setItem(STORAGE_KEY,JSON.stringify(raw));return raw.meals}return[]}return raw.meals||[]}function saveMeals(meals){localStorage.setItem(STORAGE_KEY,JSON.stringify({schemaVersion:SCHEMA_VERSION,meals}))}
function pushStack(key,a){const arr=JSON.parse(localStorage.getItem(key)||"[]");arr.unshift(a);localStorage.setItem(key,JSON.stringify(arr.slice(0,20)))}function popStack(key){const arr=JSON.parse(localStorage.getItem(key)||"[]");const it=arr.shift();localStorage.setItem(key,JSON.stringify(arr));return it}function clearStack(key){localStorage.removeItem(key)}
function computeTotals(ms){return ms.reduce((a,m)=>({cal:a.cal+(+m.calories||0),p:a.p+(+m.protein||0),c:a.c+(+m.carbs||0),f:a.f+(+m.fat||0)}),{cal:0,p:0,c:0,f:0})}
function escapeHtml(s){return(""+s).replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
function isoShift(dISO,days){const d=new Date(dISO);d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}
function kcalFromMacros(m){return(+m.protein||0)*4+(+m.carbs||0)*4+(+m.fat||0)*9}
function render(){const meals=loadMeals(),filterDate=$("#filterDate").value||todayISO(),filtered=meals.filter(m=>m.date===filterDate);const t=computeTotals(filtered),s=loadSettings(),tgt=s.targets;[["kpiCal",t.cal,tgt.cal],["kpiP",t.p,tgt.p],["kpiC",t.c,tgt.c],["kpiF",t.f,tgt.f]].forEach(([id,val,target])=>{const el=document.getElementById(id);el.textContent=(s.showRemaining?Math.max(target-val,0):val).toFixed(0);const pct=Math.max(0,Math.min(1,target?(val/target):0));el.parentElement.style.setProperty("--pct",pct);el.parentElement.classList.toggle("hit",target&&val>=target)});const tbody=$("#tbody");tbody.innerHTML="";filtered.forEach(m=>{const macrosKcal=kcalFromMacros(m),mismatch=m.calories?Math.abs(m.calories-macrosKcal):0,h=(mismatch>30)?`<div class="hint warn">⚖︎ Macros ≈ ${macrosKcal} kcal</div>`:"";const tr=document.createElement("tr");tr.innerHTML=`<td><span class="badge">${m.meal||"-"}</span><div class="small">${escapeHtml(m.category||"")} ${escapeHtml(m.time||"")}</div></td><td>${m.calories??""}${h}</td><td>${m.protein??""}</td><td>${m.carbs??""}</td><td>${m.fat??""}</td><td class="actions"><button class="btn-secondary" data-edit="${m.id}">Edit</button> <button class="btn-danger" data-del="${m.id}">Delete</button></td>`;tbody.appendChild(tr)});$$("button[data-del]").forEach(b=>b.onclick=onDelete);$$("button[data-edit]").forEach(b=>b.onclick=onEdit);$("#undoBtn").disabled=!(JSON.parse(localStorage.getItem(UNDO_STACK_KEY)||"[]").length);$("#redoBtn").disabled=!(JSON.parse(localStorage.getItem(REDO_STACK_KEY)||"[]").length);renderRollups();renderPresets()}
function renderRollups(){const meals=loadMeals(),date=$("#filterDate").value||todayISO(),d7=[],d30=[];for(let i=0;i<7;i++)d7.push(isoShift(date,-i));for(let i=0;i<30;i++)d30.push(isoShift(date,-i));const sumOn=ds=>computeTotals(meals.filter(m=>ds.includes(m.date))),t7=sumOn(d7),t30=sumOn(d30),avg=(t,n)=>({cal:t.cal/n,p:t.p/n,c:t.c/n,f:t.f/n}),a7=avg(t7,7),a30=avg(t30,30);$("#roll7").textContent=`7-day Totals: Cal ${t7.cal.toFixed(0)}, P ${t7.p.toFixed(0)}, C ${t7.c.toFixed(0)}, F ${t7.f.toFixed(0)} | Avg/day: Cal ${a7.cal.toFixed(0)}, P ${a7.p.toFixed(0)}, C ${a7.c.toFixed(0)}, F ${a7.f.toFixed(0)}`;$("#roll30").textContent=`30-day Totals: Cal ${t30.cal.toFixed(0)}, P ${t30.p.toFixed(0)}, C ${t30.c.toFixed(0)}, F ${t30.f.toFixed(0)} | Avg/day: Cal ${a30.cal.toFixed(0)}, P ${a30.p.toFixed(0)}, C ${a30.c.toFixed(0)}, F ${a30.f.toFixed(0)}`}
function currentMealFromForm(){const date=$("#date").value||todayISO(),meal=$("#meal").value.trim(),calories=+($("#calories").value||0),protein=+($("#protein").value||0),carbs=+($("#carbs").value||0),fat=+($("#fat").value||0),category=$("#category").value,time=$("#time").value||nowHM();return{date,meal,calories,protein,carbs,fat,category,time}}
function onSave(e){e.preventDefault();const form=e.target.closest("form"),m=currentMealFromForm();for(const f of["calories","protein","carbs","fat"]){if(m[f]<0||!isFinite(m[f])){alert("Please enter only non-negative numeric values.");return}if(m[f]>10000){if(!confirm("That value seems unusually high. Continue?"))return}}const mk=kcalFromMacros(m);if(m.calories===0&&mk>0)m.calories=Math.round(mk);const entry={id:form.dataset.editing||crypto.randomUUID(),...m},meals=loadMeals(),idx=meals.findIndex(x=>x.id===entry.id);if(idx>=0){const prev={...meals[idx]};meals[idx]=entry;pushStack(UNDO_STACK_KEY,{type:"edit",before:prev,after:entry});clearStack(REDO_STACK_KEY)}else{meals.push(entry);pushStack(UNDO_STACK_KEY,{type:"add",item:entry});clearStack(REDO_STACK_KEY)}saveMeals(meals);form.reset();form.dataset.editing="";$("#date").value=$("#filterDate").value;$("#time").value=nowHM();render()}
function onDelete(e){const id=e.target.dataset.del,meals=loadMeals(),idx=meals.findIndex(m=>m.id===id);if(idx===-1)return;const[removed]=meals.splice(idx,1);pushStack(UNDO_STACK_KEY,{type:"delete",item:removed});clearStack(REDO_STACK_KEY);saveMeals(meals);render()}
function onEdit(e){const id=e.target.dataset.edit,item=loadMeals().find(m=>m.id===id);if(!item)return;$("#date").value=item.date;$("#meal").value=item.meal;$("#calories").value=item.calories;$("#protein").value=item.protein;$("#carbs").value=item.carbs;$("#fat").value=item.fat;$("#category").value=item.category||"";$("#time").value=item.time||nowHM();$("#form").dataset.editing=item.id;$("#meal").focus()}
function applyActionReverse(a){const meals=loadMeals();if(a.type==="delete"){meals.push(a.item)}else if(a.type==="add"){const i=meals.findIndex(m=>m.id===a.item.id);if(i>=0)meals.splice(i,1)}else if(a.type==="edit"){const i=meals.findIndex(m=>m.id===a.after.id);if(i>=0)meals[i]=a.before}else if(a.type==="bulkAdd"){const left=meals.filter(m=>!a.items.some(x=>x.id===m.id));saveMeals(left);render();return}saveMeals(meals)}
function applyActionForward(a){const meals=loadMeals();if(a.type==="delete"){const i=meals.findIndex(m=>m.id===a.item.id);if(i>=0)meals.splice(i,1)}else if(a.type==="add"){meals.push(a.item)}else if(a.type==="edit"){const i=meals.findIndex(m=>m.id===a.before.id);if(i>=0)meals[i]=a.after}else if(a.type==="bulkAdd"){saveMeals(meals.concat(a.items));render();return}saveMeals(meals)}
function onUndo(){const a=popStack(UNDO_STACK_KEY);if(!a)return;applyActionReverse(a);pushStack(REDO_STACK_KEY,a);render()}function onRedo(){const a=popStack(REDO_STACK_KEY);if(!a)return;applyActionForward(a);pushStack(UNDO_STACK_KEY,a);render()}
const loadPresets=()=>JSON.parse(localStorage.getItem(PRESETS_KEY)||"[]"),savePresets=p=>localStorage.setItem(PRESETS_KEY,JSON.stringify(p));
function addPresetFromCurrent(){const p=currentMealFromForm(),arr=loadPresets();arr.unshift(p);savePresets(arr.slice(0,25));renderPresets();closeMenu()}
function applyPreset(idx){const p=loadPresets()[idx];if(!p)return;$("#meal").value=p.meal;$("#calories").value=p.calories;$("#protein").value=p.protein;$("#carbs").value=p.carbs;$("#fat").value=p.fat;$("#category").value=p.category||"";$("#time").value=p.time||nowHM();closeMenu()}
function renderPresets(){const sel=$("#presetPicker");if(!sel)return;const arr=loadPresets();sel.innerHTML=`<option value="">Presets…</option>`+arr.map((p,i)=>`<option value="${i}">${(""+(p.meal||"Preset")).replace(/[&<>\"']/g,s=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[s]))}</option>`).join("")}
function copyYesterday(){const target=$("#filterDate").value||todayISO(),from=isoShift(target,-1),meals=loadMeals(),y=meals.filter(m=>m.date===from).map(m=>({...m,id:crypto.randomUUID(),date:target}));if(!y.length){alert("No meals from yesterday.");return}saveMeals(meals.concat(y));pushStack(UNDO_STACK_KEY,{type:"bulkAdd",items:y});clearStack(REDO_STACK_KEY);render();closeMenu()}
function download(fn,content,type="application/json"){const b=new Blob([content],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=fn;a.click();setTimeout(()=>URL.revokeObjectURL(u),5000)}
function headersCSV(){return["id","date","meal","calories","protein","carbs","fat","category","time"]}
function toCSV(meals){const h=headersCSV();return h.join(",")+"\n"+meals.map(m=>h.map(k=>`"${(""+(m[k]??"")).replace(/"/g,'""')}"`).join(",")).join("\n")}
function exportJSON(){const payload={meta:{app:"Macro Tracker",version:APP_VERSION,exportedAt:new Date().toISOString(),schemaVersion:SCHEMA_VERSION},meals:loadMeals()};download(`macro-tracker-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(payload,null,2));closeMenu()}
function exportCSV(){const csv=toCSV(loadMeals());download(`macro-tracker-${new Date().toISOString().slice(0,10)}.csv`,csv,"text/csv");closeMenu()}
function showModal(id){$(id).classList.add("open")}function closeModal(id){$(id).classList.remove("open")}
function parseCSV(text){const lines=text.trim().split(/\r?\n/);const headers=lines.shift().split(",").map(h=>h.replace(/^"|"$/g,""));const idx=h=>headers.indexOf(h);const items=[];for(const line of lines){if(!line.trim())continue;const cols=line.match(/("(?:[^"]|"")*"|[^,]+)/g).map(c=>c.replace(/^"|"$/g,"").replace(/""/g,'"'));items.push({id:cols[idx("id")]||crypto.randomUUID(),date:cols[idx("date")]||todayISO(),meal:cols[idx("meal")]||"",calories:+(cols[idx("calories")]||0),protein:+(cols[idx("protein")]||0),carbs:+(cols[idx("carbs")]||0),fat:+(cols[idx("fat")]||0),category:idx("category")>-1?cols[idx("category")]:"",time:idx("time")>-1?cols[idx("time")]:""})}return items}
function previewImport(items){const meals=loadMeals(),ids=new Set(meals.map(m=>m.id));let n=0,u=0;items.forEach(it=>ids.has(it.id)?u++:n++);$("#importSummary").innerHTML=`Records: <b>${items.length}</b> | New: <b>${n}</b> | Updates: <b>${u}</b>`;$("#importSample").innerHTML=(items.slice(0,10).map(m=>`<li>${escapeHtml(m.date)} — ${escapeHtml(m.meal)} (${m.calories} kcal)</li>`).join(""))||"<li>No rows</li>";showModal("#importModal");window.__pendingImport=items}
function commitImport(strategy){const items=window.__pendingImport||[],meals=loadMeals(),map=new Map(meals.map(m=>[m.id,m]));if(strategy==="replaceById"){for(const m of items)map.set(m.id,m)}else{for(const m of items)if(!map.has(m.id))map.set(m.id,m)}saveMeals(Array.from(map.values()));delete window.__pendingImport;closeModal("#importModal");render()}
function importJSONFile(file){const r=new FileReader();r.onload=()=>{try{const o=JSON.parse(r.result);if(o&&Array.isArray(o.meals))previewImport(o.meals);else throw new Error("Not a Macro Tracker JSON payload.")}catch(err){alert("Import failed: "+err.message)}};r.readAsText(file)}
function importCSVFile(file){const r=new FileReader();r.onload=()=>{try{previewImport(parseCSV(r.result))}catch(err){alert("CSV import failed: "+err.message)}};r.readAsText(file)}
function toggleMenu(){$("#menu").classList.toggle("open")}function closeMenu(){$("#menu").classList.remove("open")}
document.addEventListener("click",e=>{if($("#menu").classList.contains("open")){if(!$("#menu").contains(e.target)&&e.target.id!=="menuBtn")closeMenu()}});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeMenu()})
let swReg=null;async function registerSW(){if("serviceWorker"in navigator){try{const reg=await navigator.serviceWorker.register("./service-worker.js",{scope:"."});swReg=reg;if(reg.waiting)showUpdateToast();reg.addEventListener("updatefound",()=>{const nw=reg.installing;nw&&nw.addEventListener("statechange",()=>{if(nw.state==="installed"&&navigator.serviceWorker.controller)showUpdateToast()})});navigator.serviceWorker.addEventListener("controllerchange",()=>window.location.reload())}catch(e){console.warn("SW registration failed",e)}}}
function showUpdateToast(){$("#updateToast").classList.add("show")}function doUpdateNow(){if(swReg&&swReg.waiting)swReg.waiting.postMessage({type:"SKIP_WAITING"})}
function openSettings(){const s=loadSettings();$("#targetCal").value=s.targets.cal;$("#targetP").value=s.targets.p;$("#targetC").value=s.targets.c;$("#targetF").value=s.targets.f;$("#themeSel").value=s.theme||"light";$("#showRemaining").checked=!!s.showRemaining;showModal("#settingsModal");closeMenu()}
function saveSettingsFromUI(){const s=loadSettings();s.targets.cal=clamp(+($("#targetCal").value||0),0,100000);s.targets.p=clamp(+($("#targetP").value||0),0,10000);s.targets.c=clamp(+($("#targetC").value||0),0,10000);s.targets.f=clamp(+($("#targetF").value||0),0,10000);s.theme=$("#themeSel").value;s.showRemaining=$("#showRemaining").checked;saveSettings(s);applyTheme();closeModal("#settingsModal");render()}
document.addEventListener("DOMContentLoaded",()=>{$("#ver").textContent=APP_VERSION;applyTheme();$("#filterDate").value=todayISO();$("#date").value=todayISO();$("#time").value=nowHM();$("#filterDate").addEventListener("change",render);$("#menuBtn").addEventListener("click",toggleMenu);$("#undoBtn").addEventListener("click",onUndo);$("#redoBtn").addEventListener("click",onRedo);$("#openSettingsBtn").addEventListener("click",openSettings);$("#exportJsonBtn").addEventListener("click",exportJSON);$("#exportCsvBtn").addEventListener("click",exportCSV);$("#importBtn").addEventListener("click",()=>$("#fileInput").click());$("#fileInput").addEventListener("change",e=>{const f=e.target.files[0];if(!f)return;if(f.name.endsWith(".json"))importJSONFile(f);else if(f.name.endsWith(".csv"))importCSVFile(f);else alert("Import a .json or .csv file.");e.target.value=""});$("#savePresetBtn").addEventListener("click",addPresetFromCurrent);$("#presetPicker").addEventListener("change",e=>{if(e.target.value)applyPreset(+e.target.value);e.target.value=""});$("#copyYesterdayBtn").addEventListener("click",copyYesterday);$("#settingsCancel").addEventListener("click",()=>closeModal("#settingsModal"));$("#settingsSave").addEventListener("click",saveSettingsFromUI);$("#importCancel").addEventListener("click",()=>{closeModal("#importModal");delete window.__pendingImport});$("#importCommit").addEventListener("click",()=>commitImport($("#mergeStrategy").value));$("#updateBtn").addEventListener("click",doUpdateNow);render();registerSW()});
